---
title: "SOM Markov Chain"
author: "Simon Brewer"
date: "6/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data and libraries

```{r message=FALSE}
require(markovchain)
require(kohonen)
require(RColorBrewer)
load("largeSOM.RData")
```

Make a matrix of site cluster allocations. Loop through the data frame `clus.df` made in the `runSOM.R` script and add the cluster for that particular node to the samples in the node:

```{r}
ages.uniq = rev(unique(sort(ages))) ## Reverse to get proper dynamics, you fool!
nages = length(ages.uniq)

sitesn.uniq = levels(clus.df$site)
nsites = dim(sites)[1]

poll.clus.mat = matrix(NA, nrow = nages, ncol = nsites)

for (i in 1:dim(clus.df)[1]) {
  siteID = which(sitesn.uniq == clus.df$site[i])
  ageID = which(ages.uniq == clus.df$ages[i])
  
  poll.clus.mat[ageID, siteID] <- clus.df$cluster[i]
}
```

All done? Good. Now fit a Markov Chain by MLE and visualize:
```{r}
clusts.mc = markovchainFit(as.data.frame(t(poll.clus.mat)))
clusts.mc$estimate
```

```{r}
w <- t(clusts.mc$estimate@transitionMatrix)
w <- w[which(w>0)]
plot(clusts.mc$estimate, edge.arrow.size=0.5, 
     edge.label.cex=0.75, edge.curved=0.2, #edge.width=w*5,
     vertex.size=20)
```

```{r echo=FALSE}
pdf("somMC_pollen.pdf")
plot(clusts.mc$estimate, edge.arrow.size=0.5, 
     edge.label.cex=0.7, edge.curved=0.2)
dev.off()
pdf("somMC_pollen_2.pdf")
plot(clusts.mc$estimate, edge.arrow.size=0.5, 
     edge.label.cex=0.1, edge.curved=0.2, edge.width=w*10,
     vertex.size=20)
dev.off()
```

Convert to igraph
```{r}
require(RColorBrewer)
require(igraph)
my.pal = brewer.pal(6, "Dark2")
g <- as(clusts.mc$estimate, "igraph")
min <- 0.0001
w <- clusts.mc$estimate@transitionMatrix
w <- w[which(w>0)]
plot(g, edge.label=ifelse(E(g)$prob>=min, round(E(g)$prob,3), NA),
     edge.label.cex=0.7, edge.curved=0.2, 
     vertex.color = my.pal, edge.width=2)
# plot(g, edge.label=NA, edge.arrow.size=0.5, 
#      edge.label.cex=0.7, edge.curved=0.2, 
#      edge.width=w*10, vertex.color = my.pal)
pdf("somMC_pollen_3.pdf")
plot(g, edge.label=ifelse(E(g)$prob>=min, round(E(g)$prob,3), NA),
     edge.label.cex=0.7, edge.curved=0.2, 
     vertex.color = my.pal, edge.width=2)
dev.off()
```
```{r}
my.pal = brewer.pal(6, "Dark2")
g <- as(clusts.mc$estimate, "igraph")
min <- 0.0001
w <- clusts.mc$estimate@transitionMatrix
w[which(w==0)] <- 1e-6
pdf("somMC_pollen_4.pdf")
plot(g, edge.label=ifelse(E(g)$prob>=min, round(E(g)$prob,3), NA),
     edge.label.cex=0.7, edge.curved=0.2, 
     vertex.color = my.pal, edge.width=log10(E(g)$prob*5000))
dev.off()
```

## Millenial basis

```{r}
age.step = seq(0,11000, by=1000)
for (i in 1:length(age.step)) {
  age.id = which(ages.uniq <= age.step[i]+500 & ages.uniq > age.step[i]-500)
  poll.clus.mat.tmp = poll.clus.mat[age.id,]
  clusts.mc = markovchainFit(as.data.frame(t(poll.clus.mat.tmp[,1:20])))
}
```

```{r}
# communicatingClasses(clusts.mc$estimate)
# recurrentClasses(clusts.mc$estimate)
# absorbingStates(clusts.mc$estimate)
# transientStates(clusts.mc$estimate)
steadyStates(clusts.mc$estimate)
# canonicForm(clusts.mc$estimate)
# period(clusts.mc$estimate)
```